### ISSUE TITLE
Question: Does it drops the connection at random with your server?

### ISSUE THREAD

**Issue by ebisbe** [choss/joycontrol_rest_api#1]
So I've been using the Joycontrol ( father module ) with github.com/juharris/switch-remoteplay and sometimes the connection to the switch brokes. From what it seems it's related to the other repo. 

Does this happens with your code? I'd like to try it. I'm not a python guy but I understand the code and may help ( I'm JS developer )

**Comment by choss** [comment]
I have only wrapped joycontrol. So all issues you have there are also present here. I just want to make it easier to integrate custom items.

Generally I have not observed random connection dropping with joycontrol in my tests (raspberry pi zero W, raspbian 32 bit). It drops when 
- entering a game like Animal crossing (disconnects all other controllers)
- opening the change/grip order screen

**Comment by ebisbe** [comment]
Thanks. I'll test it today and see if I have any issue.
