### ISSUE TITLE
Just published UI overlay and scripting tool that leverages the awesome joycontrol_rest_api.

### ISSUE THREAD

**Issue by MadeSimpleWorkshop** [choss/joycontrol_rest_api#12]
Thanks with your help this is possible [JoyControl Bot Designer](https://github.com/dentedghost/joycontrol_bot_designer)

**Comment by choss** [comment]
No worries! Glad to help.
I am using the rest api for my frontend over here: https://github.com/choss/joycontrol-web-interface

**Comment by choss** [comment]
I'll add a section to the readme for ~~shameless pluging~~ showing projects which use the api, to demonstrate it's readyness.

**Comment by MadeSimpleWorkshop** [comment]
Awesome and Thanks :)
