### ISSUE TITLE
Offer both or suggest pip3 over pip

### ISSUE THREAD

**Issue by MadeSimpleWorkshop** [choss/joycontrol_rest_api#3]
When installing with
sudo pip install fastapi
Error: Collecting fastapi
  Could not find a version that satisfies the requirement fastapi (from versions: )
No matching distribution found for fastapi

sudo pip install uvicorn
Error: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-ailGtW/uvicorn/

**Comment by choss** [comment]
changed it to pip3 in the readme as quick-fix 👍
