### ISSUE TITLE
Testing: /controller/connect

### ISSUE THREAD

**Issue by MadeSimpleWorkshop** [choss/joycontrol_rest_api#4]
Expected Results for /controller/connect:  it would equal sudo python3 run_controller_cli.py PRO_CONTROLLER

Actual payload: The example tries a reconnect:
{
  "controller_type": "PRO_CONTROLLER",
  "spi_firm": "",
  "reconnect_address": "E1:3F:54:0B:DE:BB"
}

Output:
INFO:     127.0.0.1:37912 - "POST /controller/connect HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
ValueError: Given data size 0 does not match size 524288.

Same result with Curl:
curl -X POST "http://0.0.0.0:8000/controller/connect" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"controller_type\":\"PRO_CONTROLLER\",\"spi_firm\":\"\",\"reconnect_address\":\"E1:3F:54:0B:DE:BB\"}"
Internal Server Error

Second Approach using basic payload

Actual payload: {
  "controller_type": "PRO_CONTROLLER"
}

Output:
INFO:root:received output report - Sub command SubCommand.REQUEST_DEVICE_INFO
INFO:     127.0.0.1:37920 - "POST /controller/connect HTTP/1.1" 200 OK

{
  "connected": "true",
  "peer": "70:48:F7:D4:8D:0D",
  "controller_type": "PRO_CONTROLLER",
  "buttons": {
    "plus": false,
    "down": false,
    "minus": false,
    "r": false,
    "r_stick": false,
    "zl": false,
    "zr": false,
    "y": false,
    "right": false,
    "home": false,
    "left": false,
    "x": false,
    "b": false,
    "l": false,
    "up": false,
    "l_stick": false,
    "capture": false,
    "a": false
  },
  "nfc_active": false,
  "left_stick": {
    "x_axis": 2048,
    "y_axis": 2048,
    "is_center": true
  },
  "right_stick": {
    "x_axis": 2048,
    "y_axis": 2048,
    "is_center": true
  }
}

Recommendations:
1) Only use the basic payload
{
  "controller_type": "PRO_CONTROLLER"
}
2)  Create a endpoint dedicated to reconnect: /controller/reconnect

3)  With the reconnect endpoint to avoid confusing replace with changemeto
{
  "controller_type": "PRO_CONTROLLER",
  "spi_firm": "",
  "reconnect_address": "??:??:??:ChangeMe"
}

**Comment by choss** [comment]
Your issue is with SPI_FIRM. 
Either leave it out/send null,  or fill it with a base64 encoded string of your SPI firmware, without line breaks! :)
I can't have an example of that of course, since the SPI-Firmware is somebody's intellectual property.
Splitting it in two calls makes it harder for **my** (java) client to use it...

**Comment by MadeSimpleWorkshop** [comment]
Thanks for all this work :)  I'm very impressed!!!

Can we add more than one try example?  New comers will just want to connect and more advanced will want to reconnect.

**Comment by choss** [comment]
I've added a couple of examples to the readme.md. Could you have a look, please?

**Comment by choss** [comment]
> Thanks for all this work :) I'm very impressed!!!

Thank you for the kind words. If you have time and a ~~high~~ frustration tollerance you can check out: https://github.com/choss/joycontrol-web-interface
