### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by ebisbe** [choss/joycontrol_rest_api#8]
When trying to use the project from a website I get the CORS issue. I'm no python expert but I'll try to read the documentation to see how to set it up. 
If you know already a quick fix would be helpful.

**Comment by choss** [comment]
Just got the relevant documentation excerpt: https://fastapi.tiangolo.com/tutorial/cors/
As I use a proxy service, I don't have this issue :+1:  A patch/PR would be appreciated, especially if it is switchable.

**Comment by choss** [comment]
I've added a patch which should help (Heavily inspired by your PR). 
Start with nocors flag to disable cors

Can you check if that solves your issue?
