### ISSUE TITLE
Update /controller/button/tap/{button_name} to a POST to allow overriding button hold time.

### ISSUE THREAD

**Issue by MadeSimpleWorkshop** [choss/joycontrol_rest_api#9]
It would be helpful for bot detection and flexibility to be able to override the default 300ms with an option payload.

Example:
`
{
  "hold_time": "575"
}

@app.patch("/controller/button/tap/{button_name}")
    async def press_controller_button_for_ms(button_name: ControllerButton):
        if cr.hold_time is not None:
            hold_time= int(base64.b64decode(cr.hold_time))
       else:
           hold_time = 300
           await app.state.switch_controller.press_controller_button(button_name)
           await asyncio.sleep(hold_time/100)
           await app.state.switch_controller.release_controller_button(button_name)
           return await controller_status()
`

**Comment by choss** [comment]
I'd put it as part of the URL of the tap api call... 
It's already on my nice-to-have list...

**Comment by choss** [comment]
added api method: example: http://\<ip\>:8000/controller/button/tap/a/0.15"

**Comment by MadeSimpleWorkshop** [comment]
Perfect,  thanks :+1:
